### ISSUE TITLE
A simple macOS app that allows you to specify starting/ending location for a route and send location updates based on real timing

### ISSUE THREAD

**Issue by billylo1** [MobileNativeFoundation/set-simulator-location#30]
Hi, first of all, thanks for open-sourcing this tool.  It has saved me lots of time.

I created a front-end for it so people can [simulate dynamic trips](https://github.com/billylo1/set-simulator-location-trip-simulator).  Demo is available [here.](https://www.youtube.com/watch?feature=player_embedded&v=oXz5YIWNWUE)

Hope it helps.

Billy.

**Comment by keith** [comment]
Nice!
